import streamlit as st
st.title("Saas Metrics Analyzer")
st.markdown("Get an AI-powered health assessment of your SaaS metrics, like a 15 minute review from an experienced investor.")
st.header("Company Info")
stage = st.selectbox("Company Stage", ["Pre-seed", "Seed", "Series A", "Series B+"])
st.header("Growth Metrics")
mrr = st.number_input("MRR - Monthly Recurring Revenue (€)", min_value=0, value=0)
mom_growth = st.number_input("MoM MRR Growth Rate (%)", min_value=0.0, max_value=1000.0, value=0.0, format="%.1f")
st.header("Unit Economics")
gross_margin = st.number_input("Gross Margin (%)", min_value=-100.0, max_value=100.0, value=0.0, format="%.1f")
nrr = st.number_input("Net Revenue Retention / NRR (%)", min_value=0.0, max_value=300.0, value=0.0, format="%.1f")
monthly_churn = st.number_input("Monthly Gross Churn (%)", min_value=0.0, max_value=100.0, value=0.0, format="%.1f")
cac = st.number_input("CAC - Customer Acquisition Cost (€)", min_value=0, value=0)
arpa = st.number_input("ARPA - Average Revenue Per Account (€/month)", min_value=0, value=0)
num_customers = st.number_input("Number of Customers", min_value=0, value=0)
st.header("Cash Position")
burn_rate = st.number_input("Monthly Burn Rate (€)", min_value=0, value=0)
cash = st.number_input("Cash in Bank (€)", min_value=0, value=0)
run = st.button("Run Analysis")